### ISSUE TITLE
Unexpected error on retrain

### ISSUE THREAD

**Issue by vgeorge** [developmentseed/pearl-backend#66]
The error I reported via chat is still present, lets track it better on this ticket.

An unexpected error is returned after `model#retrain` is sent via websocket:

```
{"message": "error", "data": {"error": "Retrain Error", "detailed": "unhashable type: 'dict'"}}
```

The payload sent is:

```
{"action":"model#retrain","data":{"name":"Amanalco de Becerra","classes":[{"name":"forest","color":"#6CA966","geometry":{"type":"FeatureCollection","features":[]}},{"name":"dry_jungle","color":"#B5C590","geometry":{"type":"FeatureCollection","features":[]}},{"name":"humid_jungle","color":"#00A884","geometry":{"type":"FeatureCollection","features":[{"type":"Feature","properties":{"class":"humid_jungle"},"geometry":{"type":"Polygon","coordinates":[[[-100.056088,19.288868],[-100.056515,19.288872],[-100.056878,19.288894],[-100.05705,19.28897],[-100.057211,19.289109],[-100.057316,19.289282],[-100.057379,19.289442],[-100.057383,19.289454],[-100.057404,19.289596],[-100.057404,19.289697],[-100.057383,19.289778],[-100.057254,19.290061],[-100.057168,19.290203],[-100.057082,19.290284],[-100.056975,19.290345],[-100.056739,19.290426],[-100.056503,19.290466],[-100.056374,19.290487],[-100.056224,19.290507],[-100.056202,19.290507],[-100.056191,19.290503],[-100.053885,19.290021],[-100.053865,19.290011],[-100.053863,19.289999],[-100.053861,19.289969],[-100.053864,19.289864],[-100.0539,19.289617],[-100.053985,19.289368],[-100.054108,19.289215],[-100.054311,19.289105],[-100.054612,19.289027],[-100.055356,19.288931],[-100.056088,19.288868]]]}}]}},{"name":"pasture","color":"#DBD746","geometry":{"type":"FeatureCollection","features":[]}},{"name":"agriculture","color":"#A96E2C","geometry":{"type":"FeatureCollection","features":[]}},{"name":"urban","color":"#F10100","geometry":{"type":"FeatureCollection","features":[]}},{"name":"without_apparent_vegetation","color":"#D0F3AB","geometry":{"type":"FeatureCollection","features":[]}},{"name":"water","color":"#486DA2","geometry":{"type":"FeatureCollection","features":[]}},{"name":"scrub","color":"#ABC964","geometry":{"type":"FeatureCollection","features":[]}},{"name":"bare_soil","color":"#B3AC9F","geometry":{"type":"FeatureCollection","features":[]}}]}}
```

Instance logs:

```
kubectl logs pearl-helm-instance-cpu-145      
E0522 14:50:13.226946   68281 memcache.go:255] couldn't get resource list for external.metrics.k8s.io/v1beta1: Got empty response for: external.metrics.k8s.io/v1beta1
[2023-05-22 13:42:43,916] - ok - GET http://pearl-helm-api/api
[2023-05-22 13:42:43,966] - ok - Received http://pearl-helm-api/api
[2023-05-22 13:42:43,966] - ok - GET http://pearl-helm-api/api/instance/145
[2023-05-22 13:42:44,020] - ok - Received http://pearl-helm-api/api/instance/145
[2023-05-22 13:42:44,021] - ok - GET http://pearl-helm-api/api/project/17
[2023-05-22 13:42:44,031] - ok - Received http://pearl-helm-api/api/project/17
[2023-05-22 13:42:44,031] - ok - GET http://pearl-helm-api/api/model/5
[2023-05-22 13:42:44,039] - ok - Received http://pearl-helm-api/api/model/5
[2023-05-22 13:42:44,039] - ok - GET http://pearl-helm-api/api/model/5/download
[2023-05-22 13:42:46,145] - ok - model: /tmp/gpu-api/model
[2023-05-22 13:42:46,853] - ok - WebSocket Connection Initialized
[2023-05-22 13:42:46,865] - ok - message: info#disconnected
[2023-05-22 13:42:46,866] - Known but unprocessed message
[2023-05-22 13:42:51,534] - ok - message: info#connected
[2023-05-22 13:42:51,535] - Known but unprocessed message
[2023-05-22 13:42:51,611] - ok - action: model#status
[2023-05-22 13:42:51,731] - ok - action: model#timeframe
[2023-05-22 13:42:51,731] - ok - GET http://pearl-helm-api/api/timeframe/127
[2023-05-22 13:42:51,744] - ok - Received http://pearl-helm-api/api/timeframe/127
[2023-05-22 13:42:51,745] - ok - GET http://pearl-helm-api/api/project/17/aoi/45
[2023-05-22 13:42:51,753] - ok - Received http://pearl-helm-api/api/project/17/aoi/45
[2023-05-22 13:42:51,754] - ok - PATCH http://pearl-helm-api/api/project/17/instance/145
[2023-05-22 13:42:51,816] - ok - Received http://pearl-helm-api/api/project/17/instance/145
[2023-05-22 13:42:51,816] - ok - GET http://pearl-helm-api/api/project/17/checkpoint/68
[2023-05-22 13:42:51,828] - ok - Received http://pearl-helm-api/api/project/17/checkpoint/68
[2023-05-22 13:42:51,828] - ok - GET http://pearl-helm-api/api/project/17/checkpoint/68/download
[2023-05-22 13:43:51,534] - ok - message: info#disconnected
[2023-05-22 13:43:51,534] - Known but unprocessed message
[2023-05-22 13:43:55,491] - ok - message: info#connected
[2023-05-22 13:43:55,491] - Known but unprocessed message
[2023-05-22 13:43:55,536] - ok - action: model#status
[2023-05-22 13:44:55,490] - ok - message: info#disconnected
[2023-05-22 13:44:55,490] - Known but unprocessed message
[2023-05-22 13:44:59,465] - ok - message: info#connected
[2023-05-22 13:44:59,466] - Known but unprocessed message
[2023-05-22 13:44:59,515] - ok - action: model#status
[2023-05-22 13:45:59,465] - ok - message: info#disconnected
[2023-05-22 13:45:59,465] - Known but unprocessed message
[2023-05-22 13:46:03,506] - ok - message: info#connected
[2023-05-22 13:46:03,507] - Known but unprocessed message
[2023-05-22 13:46:03,557] - ok - action: model#status
[2023-05-22 13:47:03,506] - ok - message: info#disconnected
[2023-05-22 13:47:03,506] - Known but unprocessed message
[2023-05-22 13:47:07,484] - ok - message: info#connected
[2023-05-22 13:47:07,484] - Known but unprocessed message
[2023-05-22 13:47:07,526] - ok - action: model#status
[2023-05-22 13:48:07,483] - ok - message: info#disconnected
[2023-05-22 13:48:07,483] - Known but unprocessed message
[2023-05-22 13:48:11,546] - ok - message: info#connected
[2023-05-22 13:48:11,546] - Known but unprocessed message
[2023-05-22 13:48:11,589] - ok - action: model#status
[2023-05-22 13:49:11,545] - ok - message: info#disconnected
[2023-05-22 13:49:11,545] - Known but unprocessed message
[2023-05-22 13:49:15,484] - ok - message: info#connected
[2023-05-22 13:49:15,485] - Known but unprocessed message
[2023-05-22 13:49:15,526] - ok - action: model#status
[2023-05-22 13:49:27,296] - ok - Received http://pearl-helm-api/api/project/17/checkpoint/68/download
[2023-05-22 13:49:28,649] - ok - PATCH http://pearl-helm-api/api/project/17/instance/145
[2023-05-22 13:49:28,770] - ok - Received http://pearl-helm-api/api/project/17/instance/145
[2023-05-22 13:49:28,911] - ok - action: model#status
[2023-05-22 13:49:29,072] - ok - message: info#disconnected
[2023-05-22 13:49:29,073] - Known but unprocessed message
[2023-05-22 13:49:54,976] - ok - message: info#connected
[2023-05-22 13:49:54,977] - Known but unprocessed message
[2023-05-22 13:49:55,027] - ok - action: model#status
[2023-05-22 13:49:55,073] - ok - action: model#retrain
[2023-05-22 13:49:55,073] - ok - starting retrain
[2023-05-22 13:49:55,084] - ok - generated 200 sample pts
Exception ignored in thread started by: <bound method ModelSrv.retrain of <lib.ModelSrv.ModelSrv object at 0x7f62db81f130>>
Traceback (most recent call last):
  File "/home/lulc/gpu/lib/ModelSrv.py", line 688, in retrain
    raise e
  File "/home/lulc/gpu/lib/ModelSrv.py", line 632, in retrain
    cls["retrain_geometry"] = geom2px(
  File "/home/lulc/gpu/lib/utils.py", line 98, in geom2px
    in_memraster = modelsrv.api.get_tile(
  File "/home/lulc/gpu/lib/api.py", line 460, in get_tile
    if AVAILABLE_MOSAICS.get(mosaic) is None:
TypeError: unhashable type: 'dict'
[2023-05-22 13:49:55,129] - ok - action: instance#terminate
[2023-05-22 13:49:55,129] - ok - Recieved Instance#Terminate
s2adeeplabv3plus
# is cuda available? False
# GPU or CPU? cpu
```

cc @ingalls @geohacker

**Comment by ingalls** [comment]
![image](https://github.com/developmentseed/pearl-backend/assets/1297009/ac2601ea-88d7-4bae-baf8-03e555a06d9b)
