### ISSUE TITLE
Can't create share urls

### ISSUE THREAD

**Issue by geohacker** [developmentseed/pearl-backend#68]
1. New project
2. Draw aoi
3. Live prediction and see inference
4. Click export > share url
5. 500 error in the api:

```
Error: ForeignKeyIntegrityConstraintViolationError: Query violates a foreign key integrity constraint. insert or update on table "aoi_timeframe_share" violates foreign key constraint "fk_aoi"
    at AOIShare.generate (file:///home/lulc/api/node_modules/@openaddresses/batch-generic/generic.js:153:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///home/lulc/api/routes/aoi-timeframe.js:391:25
::ffff:10.244.0.20 - - [01/Jun/2023:13:22:46 +0000] "POST /api//project/4/aoi/7/timeframe/6/share HTTP/1.1" 500 - "https://pearl-reforestamos.azureedge.net/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
```

@ingalls

**Comment by geohacker** [comment]
This was fixed via https://github.com/developmentseed/pearl-backend/pull/38/commits/35b7fde31ba93e242db7451f03c5681f299270a1
